name: Backend Component
description: Manage a backend component for the project
title: '[Backend Component]'
labels: ['backend']
body:
  - type: textarea
    attributes:
      label: Component Description
      placeholder: Explain what this component is responsible for.
      required: true
  - type: markdown
    attributes:
      value: |
        ### API Routes
        
        - **GET /api/endpoint:** Get data from the endpoint.
        - **POST /api/endpoint:** Create new data.
        - **PUT /api/endpoint/:id:** Update data by ID.
        - **DELETE /api/endpoint/:id:** Delete data by ID
      required: true
  - type: markdown
    attributes:
      value: |
        ### Data Flow
        
        - Data is received from clients via API requests.
        - The component processes the data and interacts with the database.
        - Processed data is returned to clients as API responses.
      required: true
