name: Backend Component
description: Manage a backend component for the project.
title: '[Backend Component]'
labels: ['backend']
body:
  - type: textarea
    attributes:
      label: Component Description
      description: Describe the purpose and functionality of the backend component.
      placeholder: Explain what this component is responsible for.
    validations:
      required: true
  - type: markdown
    attributes:
      label: API Routes
      description: List the API routes associated with this component.
      value: |
        - **GET /api/endpoint:** Get data from the endpoint.
        - **POST /api/endpoint:** Create new data.
        - **PUT /api/endpoint/:id:** Update data by ID.
        - **DELETE /api/endpoint/:id:** Delete data by ID.
    validations:
      required: true
  - type: markdown
    attributes:
      label: Data Flow
      description: Explain how data flows through this component.
      value: |
        - Data is received from clients via API requests.
        - The component processes the data and interacts with the database.
        - Processed data is returned to clients as API responses.
