blank_issues_enabled: false
contact_links:
  - name: Discussion on GitHub
    url: https://github.com/AdamsGeeky/OpSkillPath/discussions/5
    about: Need any help? Found any bug? Please chat with us via GitHub Discussions
