name: Frontend Component
description: Manage a frontend component for the project.
title: '[Frontend Component]'
labels: ['frontend']
body:
  - type: textarea
    attributes:
      label: Component Description
      description: Describe the purpose and functionality of the frontend component.
      placeholder: Explain what this component is responsible for.
    validations:
      required: true
  - type: markdown
    attributes:
      label: UI Elements
      description: List the key UI elements and features associated with this component.
      value: |
        - Element 1: Description of the element's functionality.
        - Element 2: Description of the element's functionality.
        - ...
    validations:
      required: true
  - type: markdown
    attributes:
      label: User Flows
      description: Describe the common user flows involving this component.
      value: |
        - Flow 1: Description of the flow and its steps.
        - Flow 2: Description of the flow and its steps.
        - ...
    validations:
      required: true
  - type: markdown
    attributes:
      label: Data Interaction
      description: Explain how this component interacts with backend data.
      value: |
        - Data is fetched from the backend via API requests.
        - Data is displayed to users in the frontend component.
        - Users can interact with the data and trigger updates.
        - Updated data is sent back to the backend for processing.
    validations:
      required: true

<!--
Please assign labels and appropriate milestones to this issue.
-->
